SELECT ID AS PROJECT_ID,
       (YEAR(FINISH_DATE) - YEAR(START_DATE)) * 12
       + MONTH(FINISH_DATE) - MONTH(START_DATE) AS MONTHS_COUNT
FROM project
WHERE (YEAR(FINISH_DATE) - YEAR(START_DATE)) * 12
       + MONTH(FINISH_DATE) - MONTH(START_DATE) = (
           SELECT MAX((YEAR(FINISH_DATE) - YEAR(START_DATE)) * 12
                      + MONTH(FINISH_DATE) - MONTH(START_DATE)) AS MAX_MONTHS_COUNT
           FROM project
       );
